from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer



headlines = ("Dr Seuss Enterprises Partners With Dapper Labs To Create An Entirely New Digital Collectible Experience For Fans Around The Globe",
"Dapper Labs And Circle To Transform Purchase Experience For Media & Entertainment On New Flow Blockchain",
"Victory Square Technologies Announces Completion Of Asset Purchase From Techstars 2019 Alumni Company GameOn App Inc. And Appointment Of Matt Bailey As Chief Executive Officer Of V2 Games Inc.",
"How Did A LeBron James Video Highlight Sell For $71,455? A Look At A Burgeoning Product Called NBA Top Shot.",
"Patrick Mahomes And Michael Jordan Rookie Cards Sell For All-Time Highs In Record-Setting $33 Million Auction",
"Mark Cuban: How selling stamps as a kid helped me see why digital assets are the future of business",
"Victory Square Technologies Portfolio Company, GameOn Entertainment Announces J Moses As Chairman Of Board Of Directors",
"J Moses Named Chairman Of GameOn Entertainment Technologies' Board Of Directors",
"What Is NBA Top Shot, The Digital Collectable Taking Over The Internet",
"The Whiteboard: The Toronto Raptors are finally clicking on offense",
"How JaVale McGee Embraced, Invested In Vegan Lifestyle, Became Grammy Nominated Producer Of Justin Bieber Song",
"Over $100M In Crypto Collectible NFTs Sold Over Past 30 Days",
"Mark Cuban is bullish on NFTs, and they're about to go more mainstream with an auction at Christie's",
"Christie's first digital art auction leans on blockchain and other buzzwords",
"Inside 'NBA Top Shot,' the Digital Highlights Marketplace Worth Millions",
"NBA Top Shot Seeing Record Sales, Demand During NFT Boom",
"NBA Top Shot Collectibles Continues Meteoric Rise With Over $50 Million In Sales In A Week",
"NBA Top Shot’s Next Move Is Minting Moments From Basketball History",
"Pelicans' Josh Hart Offers Blazers' McCollum Advice About NBA Top Shot",
"NBA Top Shot, the new crypto highlight phenomenon, explained",
"NBA Top Shot, CryptoPunks And More: What You Need To Know About NFTs",
"Mark Cuban: If I were to start a business right now, this is what I would do",
"NBA Players Are Now Getting In On The Top Shot Craze",
"LeBron James Lakers Highlight Sells for Record $208K on NBA Top Shot",
"OKEx Lists FLOW, The Crypto Behind NBA Top Shot NFTs",
"Zion and Ja Morant’s Card Value, Weekly Buy/Sell, NBA Top Shot Update, and Ken Goldin Interview",
"NBA Top Shot Eclipses $200M in Sales with over 65,000 Buyers Involved",
"NBA Top Shot—A Crypto-Based Platfom For Video Collectibles—Soars Past $200 Million In Total Sales",
"Crypto Conversation: It's Game On for NBA Top Shot",
"What you need to know about NFTs, the collectible digital tokens that are selling for up to millions online",
"Take advantage of a LeBron James-led team being nearly double-digit underdogs, other best bets for Wednesday",
"Why Are NBA Fans Paying Six Figures to “Buy” Highlight Clips They Could Watch for Free?",
"Collectors are spending millions of dollars every day on virtual NBA highlights. Here's what to know about NBA Top Shot.",
"Why people are buying crypto art and sports memorabilia for thousands of dollars",
"“Spending Real Money to Get Something You Can’t Even Really Explain”: What the Hell Is Going On With Bitcoin?",
"NBA Top Shot Postponed A Rare Pack Drop Due To ‘Botting Activity On The Platform’",
"SportsWatch: What is NBA Top Shot? Everything you need to know about the digital asset with over $230 million in transactions",
"SportsWatch: What is NBA Top Shot? Everything you need to know about the digital asset with over $230 million in transactions",
"Art, amulets and cryptokitties: the new frontier of crytocurrencies",
"Art, amulets and cryptokitties: the new frontier of crytocurrencies",
"How the NHL could embrace the NBA Top Shot revolution",
"What is NBA Top Shot and why is a LeBron highlight worth $208K? 'This is a real market,' Mark Cuban says",
"What is NBA Top Shot and why is a LeBron highlight worth $208K? 'This is a real market,' Mark Cuban says",
"NBA Top Shot Drop Sets Record with over 189K Users Seeking 10K Packs Costing $99",
"What Is An NFT—And Should You Buy One?",
"Best picks for the weekend, plus is Brad Stevens really on the hot seat?",
"What the NFT? VC David Pakman dumbs down the digital collectibles frenzy and why it’s taking off now",
"If you haven’t followed NFTs, here’s why you should start",
"NBA Top Shot Announced A Massive New Pack Drop With A Catch",
"NewsWatch: As rising Treasury yields spook stock investors, March looms like a lion",
"NewsWatch: As rising Treasury yields spook stock investors, March looms like a lion",
"Digital Authentication Opens New Doors For Art, Sports Collectors",
"Mark Cuban would pay $1 million for NBA Top Shot of Luka Doncic’s game-winner vs. Clippers",
"Non-Fungible Tokens 101: A Primer On NFTs For Brands & Business Professionals",
"People have spent more than $230 million buying and trading digital collectibles of NBA highlights",
"5 things to know in the NBA for Monday: How good can the New York Knicks really be?",
"5 things to know in the NBA for Monday: How good can the New York Knicks really be?",
"What Are NFTs? Is It the Future Or Just Another Crypto Fad?",
"How a 10-second video clip sold for $6.6 million",
"Would You Buy “Digital Marijuana”? Blockchain-Based “NFTs” Arrive In Cannabis.",
"NBA Top Shot: Everything you need to know about 'next level collectibles' and what it means for the league",
"The explosive (and inclusive) potential of NFTs in the creative world",
"Michael Carter-Williams Spent Nearly $3,000 On A Top Shot Of A Dunk From His NBA Debut",
"People are paying millions for clips that can be viewed for free. Welcome to the world of ‘NFTs’",
"This team is under the most pressure to win the 2021 World Series, plus explaining the NBA Top Shot craze",
"LaMelo Ball, Zion Williamson Headline NBA Rising Stars Roster Reveal on Top Shot",
"What are NFTs, and why is everyone suddenly talking about them?",
"Burned Banksy NFT Sets Art And Crypto Worlds Alight",
"Mark Cuban: Crazy NFT prices 'will settle down' over time, but the tech is here to stay",
"NBA Top Shot Announced A Series Of NBA All-Star Game Pack Drops",
"NFTs, explained",
"NFTs, explained",
"Four Things Brands Need To Know About NFTs (Non-Fungible Tokens)",
"What the Heck Are NFTs, and Why Are Grimes, Lindsay Lohan, and the Guy Who Made Nyan Cat Selling Them?",
"Millions of dollars being spent on virtual NBA moments, possible future of collectibles",
"Non-Fungible Tokens Could Change 'Culture, Period,' Says Art Specialist",
"Non-Fungible Tokens Could Change 'Culture, Period,' Says Art Specialist",
"Twitter CEO Jack Dorsey has created an NFT for the first tweet",
"Crypto collectibles are set to explode, says NBA Top Shot investor. Here are 3 trends to watch.",
"What are NFTs? Everything you need to know.",
"The sports trading card boom: Baseball cards selling for millions and the crypto craze hits NBA Top Shots",
"A Record-Setting Week—Starring Luka Doncic And Tom Brady—For Booming Sports Cards",
"Jack Dorsey Trying to Sell 1st Tweet as NFT, Highest Bid at $2.5M",
"NBA Top Shot Video of Giannis Layup in 2014 with Bucks Sells for $137K",
"Twitter CEO Jack Dorsey Sparks Huge Bidding War As $400 Million NFT Crypto Mania Spirals Out Of Control",
"LeBron James talks NBA All-Star Game concerns, COVID-19 vaccine, voting and Lakers' play",
"LeBron James talks NBA All-Star Game concerns, COVID-19 vaccine, voting and Lakers' play",
"Your Favorite Musician&#8217;s New Pandemic Hobby: Collecting Sports Cards",
"NBA Top Shot May Be The Future Of Collecting, But Challenges Remain In The Present",
": Twitter CEO Jack Dorsey is selling his first tweet — bidding is at $2.5 million",
": Twitter CEO Jack Dorsey is selling his first tweet — bidding is at $2.5 million",
"Reddit co-founder Alexis Ohanian: 'The rise of NFTs and trading card boom is going to be huge for women's sports'",
"Twitter CEO Jack Dorsey Is Selling The First Tweet Ever For Millions Of Dollars (No, Really)",
"Here are 4 NFT startups transforming the way we buy art and sports memorabilia",
"NBA Top Shot Announced Strict Marketplace Limitations As They Struggle To Handle Massive Traffic Demands",
"Rob Gronkowski will sell NFTs of his best Super Bowl moments",
"The weirdest NFTs being sold right now",
"MobileCoin, a cryptocurrency involving Signal founder Moxie Marlinspike, just raised venture funding",
"Taco Bell celebrated the return of potatoes to its menu with taco NFTs that sold out in minutes. Now, they're reselling for thousands of dollars.",
"What's Next For NBA Top Shot? The First Mint Podcast Hosts On Growth Of NFTs, Strategies And More",
"“Spending Real Money to Get Something You Can’t Even Really Explain”: What the Hell Is Going On With Bitcoin?",
"How to Fix Crypto Art NFTs' Carbon Pollution Problem",
"What’s an NFT? It’s What Makes GIFs Worth Big Bucks",
"Beeple, Artist At The Leading Edge Of A Delirious Digital Market",
"NFTs are both priceless and worthless",
"What Are NFTs?",
"NFTs Are Booming and the Music Biz Desperately Wants In",
"Pipe-Smoking Alien CryptoPunk NFT Sells For $7.5 Million",
"Sports trading card platform Alt launches with $31 million in funding and plenty of market hype",
"Art World Rocked As Digital 'NFT' Work Fetches $69.3 Mn",
"How in the World Did a “Digital Artwork” Sell for $69 Million at Christie’s?",
"Art world rocked as digital 'NFT' work fetches $69.3 million",
"Digital artwork auctions for more than $69 million, as NFT craze intensifies",
"JPG file sells for $69 million, as ‘NFT mania’ gathers pace",
"NFTs are Taking the Art World by Storm, but are They Forever? Beeple Thinks So",
"Buyer of $69 million crypto art revealed as mysterious founder of NFT fund, who says the artwork is 'worth $1 billion'",
"Fantasy Football Today's Dave Richard answers your questions about Dak Prescott, Keepers",
"Chiefs' Patrick Mahomes Launching NFT Museum Auctioning Art to Benefit Charity",
"‘Bad Luck Brian’ Sells For $36K At Auction As Retro-Memes Become The Latest Big-Ticket Item In The NFT Craze",
"$240K for a dunk highlight? Breaking down the NBA Top Shot craze",
"Patrick Mahomes Moves To Cash In On NFT Boom With ‘Museum Of Mahomes’ Digital Collectibles",
"Investment Mania: From Crypto Art to Trading Cards",
"NFTs could be the future of collecting - or a huge bubble. We talked to 3 experts about the risks to consider before buying in.",
"'It's been a motherf---ing rocket ride' : A top NFT artist who's sold over $60 million worth of crypto art breaks down how he's capitalizing on the sudden boom — and shares how he positions his own portfolio",
"Why every major entertainment company will get into NFTs, according to the VC behind NBA Top Shot",
"Cryptocurrency Price Check: Bitcoin, NFTs, and Grayscale",
"Want to Buy an NFT? Here's What to Know",
"AP Interview: Morey embraces challenges of leading 76ers",
"AP Interview: Morey embraces challenges of leading 76ers",
"From Paris Hilton to Christie's auction house: How NFTs went mainstream",
"Where Do You See NFTs At In 10 Years?",
"Jaxson Hayes sends Reggie Jackson to retirement with brutal poster dunk (Video)",
"Oasis Digital Studios And Entertainment, Technology And Lifestyle Leader, McCartney Multimedia Join Forces To Support The Development, Management, And Distribution Of AR-Enhanced NFTs",
"Where Do You See NFTs At In 10 Years?",
"Wolf Financial Brings 'Market Madness' In March With $10K Grand Prize",
"'Long the space, short the froth': Experts share 5 things to know before jumping into NFT investing, from the trading platforms to the legal risks",
"What LeBron James Highlights, Chinese Real Estate and the Mafia Have in Common",
": Tesla CEO Elon Musk is selling one of his tweets about NFTs — as an NFT",
": Tesla CEO Elon Musk is selling one of his tweets about NFTs — as an NFT",
"WTF are NFTs? Behind the Digital Asset Endorsed by Jack Dorsey and the NBA",
"LeBron James Top Shot Video of Dunk from Lakers vs. Rockets Sells for $179K",
"Oasis Digital Studios Partners With Recently Announced Digital Collectible Marketplace RARE.Store To Drop AR Enhanced NFTs",
"NFTs like NBA Top Shot are fueling a trading boom in million-dollar sports cards. The CEO of a fractional sports investing platform breaks down why digital collectibles are the 'perfect intersection of passion and profits.'",
"Kansas City Chiefs' Patrick Mahomes enters the world of NFTs",
"Victory Square Technologies Provides 2021- Q1 Corporate Update",
"What is an NFT? Non-fungible tokens explained",
"What is an NFT? Non-fungible tokens explained",
"What are NFTs and why are people paying millions for them?",
"ESE Entertainment Plans NFTs Tied To New Motor Sport Platform",
"What is an NFT? Here's why some are paying millions for digital art",
"The founder of a fractional art investing platform breaks down why he views NFTs as 'pure financial speculation' — and shares how his company allows investors to participate in the $1.7 trillion global fine art market that's historically for the ultra-wealthy",
"NBA Top Shot Reveals Every Moment Available in 2021 NBA All-Star Game Set",
"NFTs explained: These pricey assets are as weird as you think they are     - CNET",
"Liz Schimel Joins Victory Square Technologies Portfolio Company GameOn Entertainment Technologies' Board Of Directors",
"What The Heck Is An NFT And Why Is Everybody Talking About Them?",
"A guide to NFTs: What are they, and why did someone spend $69 million for one?",
"A guide to NFTs: What are they, and why did someone spend $69 million for one?",
"What is NBA Top Shot and how does it work?",
"So You Want to Mint an NFT: A Guide for Artists & Music Execs",
"Hall Of Fame Resort's Stock Rallies 30% On NFL NFT Potential",
"We talked to crypto-art investors to figure out what's driving people to spend millions on NFTs, despite no guarantee their value will increase",
"We talked to artists, wealth managers, and collectors about the NFT craze. They're worried about what they're seeing.",
"Sixers: Five things from blowout win over the Kings",
"Investing in sports cards, plus a 3-part bitcoin strategy spanning the entire ecosystem",
"Google searches for 'NFT' hit an all-time high as the user count on digital-collectible platforms beat 450,000 last week, research shows",
"NFTs Are Shaking Up the Art World—But They Could Change So Much More",
": Twitter CEO Jack Dorsey just sold his first tweet as an NFT for $2.9 million",
"John Cleese Has A Bridge To Sell You, But It’s Gonna Cost You A Lot Of Cryptocurrency",
": Twitter CEO Jack Dorsey just sold his first tweet as an NFT for $2.9 million",
"PrizePicks Announces Partnership With Prizeout, Becomes Gaming's First DFS Operator To Address Multi-Billion Dollar Challenge Of Fulfillment",
"Sports Card Marketplace Dibbs Raises $2.8 Million As NFT Mania Hits Collectibles Industry",
"The Tech Moguls and Celebrities Riding the NFT Hype and Cashing In",
"How to make, buy and sell NFTs",
"Nifty's Announces 1st NFT-Focused Social Media Platform For Creators, Collectors And Curators With Backing Of Major Investors",
"Crypto.com To Launch NFT Platform With Exclusive Content From Snoop Dogg, Aston Martin, Lionel Richie",
"Taijuan Walker Sells MLB's First NFT",
"What is an NFT? A new crypto-craze, explained",
"Tech investors pump millions into NFT start-ups as digital collectibles boom",
"What is an NFT, and why does John Cleese want to sell you his for $69.3 million?",
"Bryson DeChambeau becomes first golfer to release NFT trading cards",
"Bryson DeChambeau becomes first golfer to release NFT trading cards",
"A Venrock VC shares 5 strategies commerce startups must take to succeed in an Amazon-dominated world",
"Circle Launches Comprehensive NFT Platform & Marketplace Payments Solution",
"Flames' Tkachuk auctions 1st NHL NFT for charity",
"Lindsay Lohan On Why NFTs Are Destined For Hollywood",
"Giannis Antetokounmpo climbs Mount Tacko with poster dunk (Video)",
"Mark Cuban: The Dallas Mavericks are thinking about 'turning our tickets into NFTs'",
"What the NFT crypto art craze means for artists",
"The Margin: ‘What the hell’s an NFT?’ — ‘SNL’ explains in an amazing rap parody",
"The Margin: ‘What the hell’s an NFT?’ — ‘SNL’ explains in an amazing rap parody",
"Ars Technica’s non-fungible guide to NFTs",
"Mets' Alonso to issue NFT to aid minor leaguers",
"Mets' Pete Alonso Launching NFT, Will Donate Profits to Help Minor Leaguers",
"NFTY Jigs platform launches for developers to build interoperable games and apps",
"Mets star Pete Alonso will auction digital NFT to help minor-league baseball players",
"NBA Top Shot Announced A 48-Hour Pack Drop To Guarantee More Collectors Can Purchase Moments",
"Creator of NBA Top Shot gets $305M in funding",
"NBA Top Shot Creator Dapper Labs Gets $305M in Funding from Michael Jordan, More",
"Dapper Labs, creators of NBA Top Shot, get $305M in funding, including from Michael Jordan",
"Maker of NBA Top Shot Scores $305 Million in New Funding",
"Art’s NFT Question: Next Frontier in Trading, or a New Form of Tulip?",
"ConsenySys launches a more energy-efficient NFT ecosystem with a project from artist Damien Hirst as its first drop",
"Dapper Labs, creators of NBA Top Shot, get $305M in funding, including from Michael Jordan",
"Cryptos: Bitcoin knocking on door of $60,000 again on news from PayPal, Visa and Dapper Labs",
"Dapper Labs, Startup Behind NBA Top Shot, Raises $305M With Investment From Michael Jordan, Ashton Kutcher, Will Smith",
"Cryptos: Bitcoin knocking on door of $60,000 again on news from PayPal, Visa and Dapper Labs",
"Michael Jordan Is Among The Players Who Provided Funding To NBA Top Shot’s Creator",
"Dapper Labs, creators of NBA Top Shot, get $305M in funding",
"The NBA tries to make a slam dunk out of NFTs",
"Dapper Labs, company behind NBA Top Shot, raises $305 million while being valued at $2.6 billion",
"NBA Top Shot creator Dapper Labs receives $305M in funding from Michael Jordan, Kevin Durant, other NBA stars",
"Dapper Labs, creators of NBA Top Shot, get $305M in funding",
"Tennis Player Oleksandra Oliynykova Sells Patch of Skin on Right Arm as NFT for $5K",
"Investment platform Dibbs is blending traditional card trading with NFT technology to capitalize on the billion-dollar market, after raising $2.8 million in funding",
"Traders Worry Reopening Will Stifle NFT Rally",
"NFT art marketplace SuperRare closes $9 million Series A",
"Dapper Labs, creators of NBA Top Shot, get $305M in funding, including from Michael Jordan",
"Dapper Labs, creators of NBA Top Shot, get $305M in funding",
"NBA Top Shot Maker Collects $2.6 Billion Valuation On NFT Fervor",
"NBA Top Shot maker Dapper Labs is now worth $2.6 billion thanks to half of Hollywood, the NBA, and Michael Jordan",
"These Gen Z VCs are getting in on the NFT frenzy — here are the 4 NFTs they've collected so far",
"Dapper Labs, creators of NBA Top Shot, get $305M in funding, including from Michael Jordan",
"Dapper Labs, creators of NBA Top Shot, get $305M in funding",
"NBA Top Shot, MLB Team Values And Daniil Medvedev: This Week’s Most Interesting Sports Business Stories",
"Rams' Taylor Rapp goes NFT route to support Chinese Americans",
"Q&A with Dapper Labs CEO Roham Gharegozlou on future of NBA Top Shot, sports digital collectibles",
"Negro League researcher Cam Perron talks about his new book, the Negro Leagues, and the times to come",
"NBA Top Shot maker Dapper Labs just nabbed another $305 million investment from the likes of Michael Jordan and Will Smith",
"Coatue, Michael Jordan, Kevin Durant, A16z, And More Than 30 Other NBA And NFL Players And VCs Invest $305 Million In Dapper Labs, Makers Of NBA Top Shot And Flow Blockchain",
"Would You Buy an NFT?",
"Q&A with Dapper Labs CEO Roham Gharegozlou on future of NBA Top Shot, sports digital collectibles",
"NFL player Taylor Rapp is launching an NFT collection to fight anti-Asian hate. A chief investment officer breaks down why NFTs are 'psychological assets' that could surge when a large network of people assigns value to them.",
"6 NFT Twitter Accounts To Follow For Non-Fungible Token Growth",
"10 Largest Venture Rounds In Crypto And Blockchain",
"Revenge Of The Winklevii",
"Analysts Suggest 'Silent Crash' May Be Underway As NFT Prices Floors Plummet",
"Fantom Blockchain Announces Formula One Sponsorship",
"New Fantasy Feature Ups The Ante On The Masters Digital Experience",
"Baseball card giant Topps is going public via a $1.3 billion SPAC deal",
"Baseball card giant Topps is going public via a $1.3 billion SPAC deal",
"Have a great idea for an NFT startup? Pitch it to Ashton Kutcher, Snoop Dogg, Mark Cuban for a share of a $1 million.",
"Owner Of NBA’s Kings To Offer To Pay Players In Bitcoin",
"Opinion: The Doge Days Are Over. You Invested in Dogecoin, Now What?",
"How a 10-second video clip sold for $6.6 million",
"Peyton, Eli Manning to Launch NFT Artwork; Proceeds to Be Donated to Charity",
"NFTs: How Baseball Cards Led To A Beeple Aha Moment",
": Playboy is getting into the NFT market with plans to create digital art from its own photography",
": Playboy is getting into the NFT market with plans to create digital art from its own photography",
"The Major Label NFT Strategy Will Focus on Long-Term Revenue",
"Deshaun Watson, Rich Paul And Mukesh Ambani: This Week’s Most Interesting Sports Business Stories",
"DraftKings Scores With New Investments And Hire, Pushing Further Into Media And Content Creation",
"Luka Garza makes history and sells NFT for more than $40,000",
"NFT Market Surges 2,100% to $2 Billion in Q1 Sales",
"How baseball card mania is colliding with NFT boom to revive Topps and change the game for dealers",
"Amid Skepticism Over NFTs, Business Strategist Sees Opportunity",
"Here's who just got rich from the Coinbase debut",
"Beyond Crypto Art: Exploring The NFT Landscape In Music, Gaming, And Industrial Design",
"Detroit’s native son, billionaire Dan Gilbert, makes the case for his town",
"What is NBA Top Shot and how can I buy an NFT 'moment' of spectacular plays?",
"For $14K you can buy an NFT of a spectacular Giannis 'moment' from the Bucks superstar's rookie year",
"Coinbase’s first employee in 2013 cold-emailed the founders for a job — and was paid in bitcoin for 3 years",
"Terra Virtua: What NFTs Can Teach Us About Establishing A Brand In An Emerging Market",
"Legendary investor Ron Conway tells us Coinbase is the new Google. Here's what that means for the next wave of startup founders.",
"Mark Cuban Invests In NFT Data Aggregator, CryptoSlam",
"People on the West Coast are largely driving the conversation around crypto art, with Middle America showing the least interest",
"LeBron James NBA Top Shot moment of dunk honoring Kobe Bryant auctions for $387,600",
"NFTs with Wisconsin connections: Giannis, Tyler Herro and an artist called Beeple who sold a digital collage for $70 million",
"LeBron James NBA Top Shot moment of dunk honoring Kobe Bryant auctions for $387,600",
"LeBron James Dunk Paying Homage to Kobe Bryant Sells for Record $386K on NBA Top Shot",
"People are buying and selling crypto collectibles in a $250 million market - check out the sites where you can browse and bid on them",
"The NBA Playoff Races Heat Up, Plus: Weekly Card Buys and Darren Rovell Interview",
"It's not NBA Top Shot, Beeple or a tweet, but IBM thinks patents should be NFTs",
"Amid Slowing NFT Demand NBA Top Shot Creator Raises Capital Again, Tripling Valuation",
"NFT Craze Catching On in Media Industry",
"Alex Rodriguez, Europe’s Super League And The NFL Draft: This Week’s Most Interesting Sports Business Stories",
"Backed by Nas and Dapper Labs CEO, SportsIcon launches to deliver NFTs bundled with exclusive athlete content",
"Topps Sells Out MLB NFTs In 70 Minutes: Live Pack Opening On Benzinga's 'SPACs Attack' (Video)",
"Nets' Spencer Dinwiddie says it's 'realistic' he can come back this season from partially torn ACL",
"NFT sale prices are dropping, but experts say it might not be a bad sign",
"NBA Top Shot is booming, but users report trouble cashing out after sales of the collectable NFTs",
"What Is Zed Run? Ethereum, NFTs And Horses Combine For Digital Racehorse Experience",
"NBA Top Shot Weekly with Brian Scalabrine",
"Future Jaguar Trevor Lawrence is the next athlete to be paid in crypto",
"NBA Top Shot customers can't get their money out. Experts are confounded",
"NBA Top Shot customers can't get their money out. Experts are confounded",
"Binance, the world's largest cryptocurrency exchange, is launching an NFT marketplace",
"The Golden State Warriors are auctioning team memorabilia collections as NFTs",
"Golden State Warriors Launch NFT Collection, Becoming First U.S. Sports Team To Release Own NFTs",
"Warriors first pro team to launch NFT collection",
": NBA’s Golden State Warriors become first pro sports team to release its own NFTs",
": NBA’s Golden State Warriors become first pro sports team to release its own NFTs",
"Tyrese Haliburton Gave Kings Staffer His Visa Card to Buy Top Shot Pack for Him",
"Binance, World’s Largest Crypto Exchange, Aims To Disrupt NFTs With Its DeFi Playbook",
"The Golden State Warriors are the first pro sports team to launch an NFT collection",
"Golden State Warriors first pro sports team to launch NFT collection",
"A Guide To Non-Fungible Tokens, The Future Of Art",
"Dapper Labs Reveals Plans For Next NFT Marketplace After NBA Top Shot",
"A Coinbase-backed start-up quietly powering the NFT boom raises new funding",
"UFC, WME Parent Endeavor IPO: What Investors Need To Know",
"Kwity Paye to Release 1-of-a-Kind NFT After Being Selected in 2021 NFL Draft",
"NFTs Combat Bubble Burst Claims As Real Life Use Cases Push Forward",
"The Risks & Rewards of Growth Hacking & Clout Chasing with BitClout",
"WMG Partners With Genies to Turn Artists Into Avatars & Sell NFT Gear",
"Warner Music Group Dives Into NFT Fray With Genies Partnership To Create Artist Avatars",
"NBA Top Shot Announced ‘Trade Tickets’ For Unwanted Moments And A Chance To Get Rare Season One Packs",
"Avatar startup Genies scores $65 million in funding round led by Mary Meeker’s Bond",
"EBay Looking Into NFT Marketplace: How The Auction Site Could Gain More Monetizable Users",
"Warriors Sell 327 NFTs of Artwork of Championship Tickets, Rings for Over $2m",
"The latest hockey player to enter the realm of NFTs? Hall of Famer Bryan Trottier",
"NBA union executive leads talks to help players make more money from NFTs",
"How NBA Top Shot turned dunks into digital gold",
"How NBA Top Shot turned dunks into digital gold",
"Imran Potato Drops NFTs To Give Fans Access To Potato Product",
"Meet Neuno’s Natalie Johnson, One Of The Female Leaders Revolutionizing Fashion & Luxury In The Metaverse",
"Creator Coins Enable Influencer Economies. Rally Plans To Mint A Million Of Them",
"NBA players are making a fortune from NFTs. UFC fighters may not be so lucky",
"NBA players are making a fortune from NFTs. UFC fighters may not be so lucky",
"Sequoia Games looks to capitalize on NBA Top Shot fever with an AR tabletop game",
": EBay to allow NFT sales on its platform",
": EBay to allow NFT sales on its platform",
"Daily Crunch: As tech stocks lose their luster, SPACs are on the rise",
"Jack Dorsey's $2.9 million NFT tweet sale may be only the beginning",
"Jack Dorsey's $2.9 million NFT tweet sale may be only the beginning",
"Animoca Brands Raises US$88,888,888 Based On Valuation Of US$1 Billion",
"What Exactly Is An NFT And Why Should You Care?",
"Huobi Ventures Launches With $100M For Early Stage DeFi Investments, Mergers And Acquisitions",
"Charlotte Hornets Launches NFT Ticket With NBA Top Shot Parent Dapper Labs",
"EXCLUSIVE: How Alkaline Water Signed Shaquille O'Neal As Brand Ambassador",
"Victory Square Portfolio Company, GameOn Entertainment Technologies Inc. Receives Conditional Approval To List Under The Symbol CSE: GET",
"This Week in Apps: Apple talks App Store fraud, responds to antitrust complaints; Facebook growth is slipping",
"No Slam Dunk For Plaintiffs In NBA Top Shot Moments Class Action Lawsuit",
"What are NFTs? The booming blockchain-based movement, explained",
"Dapper Labs Leads $1.14 Million Seed Round Investment In Digital Collectibles Company",
"Bass column: The sports card and NFT markets are hot. Are you ready to sell? To buy?",
"NBA Top Shot Reveals New 'Hustle and Show Moments' Featuring Damian Lillard and More",
"OneOf wants to sell you a John Legend NFT",
"Animoca Brands And Hedera Announce Helix Warp And NFT-based Football Game",
"Naomi Osaka, Microchips And Digital Collectibles: This Week’s Most Interesting Sports Business Stories",
"Calaxy Creates The Creators’ Galaxy On Blockchain",
"Calaxy, Built On The Hedera Network, Adds Initial Advisors From Dapper Labs, Liquefy, BlueSky, And Centre Consortium",
"Reddit Co-Founder Alexis Ohanian Leads Investment In ‘Picks And Shovels’ Blockchain Firm",
"Spencer Dinwiddie’s Calaxy Names Dapper Labs CEO, Three Others, As Advisors",
"Dapper Labs backs art hardware startup Infinite Objects in $6 million seed raise",
"Hornets' LaMelo Ball to Release NFTs Ahead of NBA's Rookie of the Year Announcement",
"Bucs' Tom Brady 'Big Believer' in Cryptocurrency, Discusses NFT Company 'Autograph'",
"Are Movies And Streaming The Next Frontier For NFTs?",
"Top NFT And DeFi Projects to Watch in 2021",
"MLB to diversify, expand on NFT offerings this fall",
"NBA, MLB, NFL, And NHL Partner Fanatics Launches NFT Marketplace",
"NFTs Are Crashing and Who Could Have Seen This Coming Other Than Basically Anyone?",
"'A lot of history': IOC creates NFT versions of past Olympic pins for Summer Games in Tokyo",
"'A lot of history': IOC creates NFT versions of past Olympic pins for Summer Games in Tokyo",
"Thousands Descend on Miami to Glorify Bitcoin",
"These Are The 12 Biggest Fundraising Rounds In Crypto And Blockchain History",
"Todd and Rahul’s Angel Fund closes new $24 million fund",
"The NFT boom has gone bust — for now",
"FootballCoin Launches Euro 2020 Fantasy Game With Collectable NFTs And XFC Prizes",
"Milwaukee Bucks launch their own NFTs to celebrate 1971 championship",
"E3 2021: NFTs are coming to 'Blankos Block Party' and other video games",
"Sneaker community startup SoleSavy raises $12.5 million Series A to build an end-to-end sneakersphere",
"NFT marketplace startup Rarible closes $14.2 million Series A",
"No end to investment whiplash in meme stocks, cryptocurrency and more",
"Andreessen Horowitz triples down on blockchain startups with massive $2.2 billion Crypto Fund III",
"Beeple, the artist behind $69M NFT auction, unveils website where you can buy moments as NFT collectibles",
"The Beeple Guy Joins Forces With the Pitchfork Guy to Sell Moments in History as NFTs",
"Camila Cabello, Paris Hilton, and Priyanka Chopra Invest in Avatar Startup Genies",
"NFTs And The Missing Layer Of Utility",
"EWorld Companies, Inc. Announces Upcoming Release Of New Limited Edition Bitcoin Wine NFT",
"Trail Blazers, StormX Agree to NBA's 1st-Ever Cryptocurrency Jersey Patch Contract",
"Every NBA Team's Biggest Regret This Season",
"NFT sales volume surges to $2.5 billion in 2021 first half",
"NFT Marketplace CEO Explains Why The Industry Is Moving Beyond Ideological Purists",
"76ers' Daryl Morey Appears to Buy Ben Simmons Top Shot Highlight Amid Trade Rumors",
"MLB, Candy Digital will offer World Series ring with Los Angeles Dodgers NFT",
": Gary Vaynerchuk says this is how you can tell if an NFT will be a winner over the next 10 years",
": Gary Vaynerchuk says this is how you can tell if an NFT will be a winner over the next 10 years",
"USD Coin Creator Circle Going Public Via SPAC: What Investors Should Know")

# function to print sentiments of the sentence.

def sentiment_scores(headlines):

    # Create a SentimentIntensityAnalyzer object.
    sid_obj = SentimentIntensityAnalyzer()

    # polarity_scores method of SentimentIntensityAnalyzer object gives a sentiment dictionary. which contains pos, neg, neu, and compound scores.
    x = 0
    y = []
    for i in headlines:
        print(headlines[x])
        sentiment_dict = sid_obj.polarity_scores(headlines[x])

        # decide sentiment as positive, negative and neutral
        if sentiment_dict['compound'] >= 0.05 :
            y.append("Positive")
            print(sentiment_dict['compound'])
            x += 1
        elif sentiment_dict['compound'] <= - 0.05 :
            y.append("Negative")
            print(sentiment_dict['compound'])
            x += 1
        elif sentiment_dict['compound']  > -0.05 and sentiment_dict['compound'] < 0.05 :
            y.append("Neutral")
            print(sentiment_dict['compound'])
            x += 1
        else:
            pass
    textfile = open("topshotSentiments.txt", "x")
    for element in y:
        textfile.write(element + "\n")
    textfile.close()



# Driver code
if __name__ == "__main__" :
    # function calling
    sentiment_scores(headlines)
