folders = ('Understanding Small Disadvantaged Businesses',
How To Start A Trucking Business,
X Home Based Small Business Opportunities in 2021,
Small Business Loans For U.S. Veterans,
Guide To Unemployment For Small Business Owners,
How To Start An Non Profit Charity Organization,
X Ideas For Small Town Businesses,
How To Find Free Customer Database Software For A Small Business,
How To Find Real Estates Investors In Your Area,
What Is PPC? And How Can A SMB Use It?,
Guide To Digital Marketing For Small Business Owners,
How To Does Adwords Work? And How Can A SMB Use It?,
What Is Local SEO? And How Can A SMB Use It?,
What Is Email Marketing? And How Can A SMB Use It?,
X Creative Low Cost Way To Advertise A Small Business in 2021,
X Best Receipt Scanning Apps for Small Businesses,
What Is a Time Log? How Can You Use It To Improve Efficiency?,
How To Create An Employee Training Program,
Whis Is Time Management Important?,
X Free Apps All Contractors Should Be Using,
X Free Apps All Entrepreneurs Should Be Using,
Guide To Automation in Your SMB Workplace,
X Free Business Apps All Small Businesses Should Be Using,
X Strategies That Can Your Improve Your Small Business,
X Culture Tips for Increasing Efficiency in the Workplace in Your,
How to Prioritize Work Effectively and Achieve Your Goals,
Guide To Tracking Employee Time,
Invoice Factoring Guide: Everything You Should Know,
X Consulting Invoice Templates And How To Create A Custom One,
How To choose The Best Invoice App For Your Small Business,
X Mechanic Invoice Templates And How To Create A Custom One,
X Rental Invoice Templates And How To Create A Custom One,
X HVAC Service Invoice Templates And How To Create A Custom One,
What Is The Difference Between a Quote And an Invoice?,
X Catering Invoice Templates And How To Create A Custom One,
X Car Invoice Templates And How To Create A Custom One,
X Handyman Invoice Templates And How To Create A Custom One,
What Is The Difference Between a Receipt And an Invoice?,
What Is The Difference Between a Invoice And a Statement?,
X Donation Invoice Templates And How To Create A Custom One,
X Customer Retention Strategies All Small Businesses Should Know,
XX Customer Service Strategies Every Business Owner Should Know,
How To Hire Employees)

for i in folders:
    print(i)
