import os

names = ["Guide To Small Business Loan Forgiveness in 2021",
"How To Choose The Best Credit Card For Your Small Business",
"X Small Business Loans for Women and How To Apply",
"How To Start A Small Business in Colorado",
"What Is A Gig Worker?",
"How To Write A Rent Receipt",
"X Business Ideas for Teens",
"Most Profitable Woodworking Projects to Build and Sell",
"Cash Receipt Templates",
"How To Find The Right Small Business Wholesale Suppliers",
"Free Employee Scheduling Software For Your Business",
"X Mileage Tracker Apps That Will Track Your Mileage Easily",
"Can 1099 Employees File for Unemployment?",
"Donation Receipt Template (501(c)(3) Non-Profit)",
"How To Find Employees For Your Small Business",
"X Steps To Writing A Simple Receipt",
"How To Create A Simple Email Receipt",
"How to Evaluate an Employee",
"How To Start An Insurance Franchise in The USA",
"How You Can Improve Office (and Remote) Etiquette in 2021",
"How To Choose The Best Real-Estate Franchise For You in 2021",
"X Rental Business Ideas to Start in 2021",
"How To Choose A Small Business Security System in 2021",
"The Pros And Cons Of Outsourcing in 2021",
"X Business Apology Letter Examples",
"How to Delegate Tasks Effectively",
"X Common Types of Small Business Fraud in 2021",
"What are White Label Services and How Do You Use Them",
"What Is A Bank Receipt?",
"X Cleaning Franchises You Can Start in 2021",
"Receipts 101: How To Create Digital Receipts",
"How To Choose Best Donut Franchise Business in 2021",
"Retail Store Layout Design and Planning Guide",
"White Label vs Private Label Products: What's The Difference?",
"How to Have an Estate Sale",
"The Best Franchises for Veterans in 2021",
"How and Why To Get BBB Accreditation in 2021",
"X Most Profitable Small Businesses in 2021",
"Tire Franchise Opportunities Guide 2021",
"Where To Sell Your eBooks Online in 2021",
"How To License A Product in 2021",
"X Laundromat Franchise Opportunities for 2021",
"What is the Difference Between Coaching and Mentoring",
"How To Choose The Best Senior Care Franchise in 2021",
"What Is A Shipping Invoice?",
"How To Choose Best Storage Franchise Business in 2021",
"How To Write A Trucking Invoice (Template)",
"Welding Projects To Make Money At Home",
"How To Choose Best Bubble Tea Franchise Business",
"How To Choose The Best Cleaners Franchise Business",
"X Small Family Run Business Ideas to Build Your Future",
"A Guide To Home Inspection Franchise Opportunities",
"A Guide To Home Hotel Franchise Opportunities",
"How to Set Up & Open a Pop-Up Shop in 2021",
"How to Sell at Farmers Markets as a Business",
"How To Choose Best Juice Bar Franchise Business in 2021",
"How To Write A Self-Employed Invoice (Template)",
"How To Find Sewing Projects That You Can Sell",
"Guide to Employee Management in 2021 (Remote and In Person)",
"Most Profitable Vending Machines in 2021",
"How To Find The Best Blank Wholesale T-Shirts Distributor",
"A Simple Guide for Opening a Gym in 2021",
"How To Write A Vehicle Towing Receipt (Template )",
"How To Find The Best Daycare Franchise Opportunities for 2021",
"Fun Contest Ideas for Workplace, Office, and Remote",
"How Does Unemployment Work for Employers?",
"What is Amazon Locker and How Can it Benefit Your Business",
"How To Decorate A Small Office",
"How to Legally Fire an Employee",
"How to Create a Great Internship Program in 2021",
"How to Negotiate Payment Terms with Vendors",
"How To Write a Notary Service Invoice (Template)",
"How To Choose The Best Oil Change Franchise in 2021",
"How To Choose The Best Pest Control Franchise in 2021",
"The Nine Types of Private Equity Simply Explained",
"How and What to Sell at Flea Markets and Garage Sales in 2021",
"How To Write A Bakery Invoice (Template)",
"The Best Real-Time Document Collaboration Tools in 2021",
"How To Write A Freight Invoice (Template)",
"How Consignment Works and is it an Option for A Small Businesses?",
"Guide to Determining Your Business's Market Value",
"Employee Background Checks: What's Legal and What Is Checked",
"How To Write A Musician Invoice (Template)",
"Small Business Ideas for Those Who Enjoy the Outdoors in 2021",
"How To Rent An Office In 2021",
"How to Sell Your Crafts Online in 2021",
"How To Write An Attorney Invoice (Template)",
"What Is a Venture Capital Due Diligence Checklist?",
"How To Invoice As A Video Production Freelancer",
"How To Write A Daycare Invoice (Template)",
"Create a Positive Workplace Culture For Your Employees in 2021",
"X Things You Need to Know About Selling Services",
"How To Write An Interior Design Invoice (Template)",
"X Strategies to Keep Your Small Business Organized in 2021",
"X Best Interview Questions for Small Businesses in 2021",
"How To Write a Locksmith Invoice (Template)",
"X Most Profitable Types of Restaurants in 2021",
"X Things To Know Before Joining Service Corps of Retired Executives (SCORE)",
"How To Write A Subcontractor Invoice (Template)",
"X Signs You Have A Bad Hire and How To Deal With Them",
"How To Write A Pest Control Invoice (Template)",
"How To Write A Therapist Psychologist Invoice (Template)",
"Best Time Clock Apps for Remote Workers",
"How to Use Social Media to Recruit and Hire in 2021",
"How to Accept Bitcoin Payments at Your Business",
"What is Employee Efficiency? How Do You Improve It?",
"X Things To Know About The SBA Disaster Assistance Loans for Coronavirus",
"How to Train Your New Employees Effectively",
"How to Gain Respect from Employees",
"What Should a New Manager do on the First Day?",
"How To Write An Actor Invoice (Template)",
"How To Write An Event Planner Invoice (Template)",
"Funding Options for Hispanic-Owned Businesses in 2021",
"How To Write A Makeup Artist Invoice (Template)",
"X Top Remote Work Tools in 2021",
"How to Write a Career Development Plan for Your Employees",
"A Small Business Guide To Short Term Lenders in 2021",
"How To Write a Snow Plowing Invoice (Template)",
"How To Write an Architecture Invoice (Template)"]
# make sure to pay  attention to  folder path if renamed in system else error

base_path = '/Users/dillondaniel/desktop/fractl/'
 # use raw string if you would use backslash e.g. r'c:\xampp\htdocs\site\'
for x in names:
    os.mkdir(os.path.join(base_path, x))
